// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UGCase.Models.Context;

#nullable disable

namespace UGCase.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240821202609_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UGCase.Models.musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("musteris");
                });

            modelBuilder.Entity("UGCase.Models.musteriFatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("faturaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("faturaTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("musteriId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("odemeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("musteriId");

                    b.ToTable("musterisFatura");
                });

            modelBuilder.Entity("UGCase.Models.musteriFatura", b =>
                {
                    b.HasOne("UGCase.Models.musteri", "Musteri")
                        .WithMany("MusteriFaturalar")
                        .HasForeignKey("musteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("UGCase.Models.musteri", b =>
                {
                    b.Navigation("MusteriFaturalar");
                });
#pragma warning restore 612, 618
        }
    }
}
